### ISSUE TITLE
The csproj project properties must be updated

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.github.template#52]
The *.csproj file that is generated when creating a new repository has some defects:

- [x] an old version of .NET Core is targetted.  This must be updated to a newer version (net6.0)
- [x] We're still using the older way to reference to the LICENSE file
- [x] The folder `docs/static/img` still contains old Arcus logo's
- [x] There is no icon.png file present in the `docs/static/img/` folder
- [x] The csproj must contain an itemgroup with these properties:
  ```
  <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\..\docs\static\img\icon.png" Pack="true" PackagePath="\"/>
    </ItemGroup>
  ```

**Comment by stijnmoreels** [comment]
Yes, that's great, awesome. Good to keep this up-to-date. 👍
